communications/urls.py
from django.conf.urls import  url
from . import views
comm_urls = [

    url(r'^$',views.comm_detail, name='comm_detail'),
    url(r'^edit/$',views.comm_cru, name='comm_update'),




]

crmapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from marketing.views import HomePage
from subscribers import views
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from accounts.views import AccountList,account_cru
from accounts.urls import account_urls
from django.conf import settings
from django.conf.urls.static import static
from accounts.urls import account_urls
from contacts.urls import contact_urls
from contacts.views import contact_cru
from communications.views import comm_cru
from contacts.views import ContactDelete
from communications.urls import comm_urls
from communications.views import CommDelete
admin.autodiscover()

urlpatterns = [
    # Marketing pages
     url(r'^$', HomePage.as_view(), name="home"),
     url(r'^signup/$',views.subscriber_new, name='sub_new'),
     url(r'^admin/', include(admin.site.urls)),
      # Login/Logout URLs
     url(regex=r'^login/$', view=login, kwargs={'template_name': 'login.html'},name='login'),
     url(regex=r'^logout/$', view=logout, kwargs={'next_page': '/'}, name='logout'),
     # Account related URLs
     url(r'^account/new/$',account_cru, name='account_new'),
     url(r'^account/list/$',AccountList.as_view(), name='account_list'),
     url(r'^account/(?P<uuid>[\w-]+)/', include(account_urls)),
     # Contact related URLS
     url(r'^contact/new/$',contact_cru, name='contact_new'),
     url(r'^contact/(?P<uuid>[\w-]+)/', include(contact_urls)),
     url(r'^contact/(?P<pk>[\w-]+)/delete/$',ContactDelete.as_view(), name='contact_delete'),
     # Communication related URLs
     url(r'^comm/new/$',comm_cru, name='comm_new'),
     url(r'^comm/(?P<uuid>[\w-]+)/', include(comm_urls)),
     url(r'^comm/(?P<pk>[\w-]+)/delete/$',CommDelete.as_view(), name='comm_delete'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

communications/models.py
from django.db import models
from django.contrib.auth.models import User

from accounts.models import Account

from shortuuidfield import ShortUUIDField


class Communication(models.Model):
    uuid = ShortUUIDField(unique=True)
    TYPE_LIST = (
        (1, 'Meeting'),
        (2, 'Phone'),
        (3, 'Email'),
    )
    subject = models.CharField(max_length=50)
    notes = models.TextField()
    kind = models.PositiveSmallIntegerField(choices=TYPE_LIST)
    date = models.DateField()
    owner = models.ForeignKey(User)
    account = models.ForeignKey(Account)
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'communications'

    def __unicode__(self):
        return u"%s" % self.subject

    @models.permalink
    def get_absolute_url(self):
        return 'comm_detail', [self.uuid]

    @models.permalink
    def get_update_url(self):
        return 'comm_update', [self.uuid]

    @models.permalink
    def get_delete_url(self):
        return 'comm_delete', [self.id]

communications/forms.py
from django import forms

from .models import Communication

class CommunicationForm(forms.ModelForm):
    class Meta:
        model = Communication
        fields = ('subject', 'notes', 'kind', 'date', 'account',)
        widgets = {
            'subject': forms.TextInput(
                attrs={
                    'placeholder':'Subject',
                    'class':'form-control'
                }
            ),
            'notes': forms.Textarea(
                attrs={
                    'placeholder':'Add notes...',
                    'class':'form-control'
                }
            ),
            'kind': forms.Select(
                attrs={
                    'placeholder':'Type',
                    'class':'form-control'
                }
            ),
            'date': forms.DateInput(
                attrs={
                    'placeholder':'Date',
                    'class':'form-control'
                }
            ),
        }

communications/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from .models import Communication
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import CommunicationForm
from django.shortcuts import get_object_or_404
from accounts.models import Account
from django.utils.decorators import method_decorator
from django.views.generic.edit import DeleteView
from django.http import Http404

@login_required()
def comm_detail(request, uuid):

    comm = Communication.objects.get(uuid=uuid)
    if comm.owner != request.user:
            return HttpResponseForbidden()

    return render(request, 'communications/comm_detail.html', {'comm':comm})
@login_required()
def comm_cru(request, uuid=None, account=None):

    if uuid:
        comm = get_object_or_404(Communication, uuid=uuid)
        if comm.owner != request.user:
            return HttpResponseForbidden()
    else:
        comm = Communication(owner=request.user)

    if request.POST:
        form = CommunicationForm(request.POST, instance=comm)
        if form.is_valid():
            # make sure the user owns the account
            account = form.cleaned_data['account']
            if account.owner != request.user:
                return HttpResponseForbidden()
            # save the data
            form.save()
            # return the user to the account detail view
            if request.is_ajax():
                return render(request,
                              'communications/comm_item_view.html',
                              {'comm':comm, 'account':account}
                )
            else:
                reverse_url = reverse(
                    'account_detail',
                    args=(account.uuid,))
                return HttpResponseRedirect(reverse_url)
        else:
            # if the form isn't valid, still fetch the account so it can be passed to the template
            account = form.cleaned_data['account']
    else:
        form = CommunicationForm(instance=comm)

    # this is used to fetch the account if it exists as a URL parameter
    if request.GET.get('account', ''):
        account = Account.objects.get(id=request.GET.get('account', ''))

    variables = {
        'form': form,
        'comm':comm,
        'account': account
    }

    if request.is_ajax():
        template = 'communications/comm_item_form.html'
    else:
        template = 'communications/comm_cru.html'

    return render(request, template, variables)
class CommMixin(object):
    model = Communication

    def get_context_data(self, **kwargs):
        kwargs.update({'object_name':'Communication'})
        return kwargs

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CommMixin, self).dispatch(*args, **kwargs)

class CommDelete(CommMixin, DeleteView):
    template_name = 'object_confirm_delete.html'

    def get_object(self, queryset=None):
        obj = super(CommDelete, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        account = Account.objects.get(id=obj.account.id)
        self.account = account
        return obj

    def get_success_url(self):
        return reverse(
            'crmapp.accounts.views.account_detail',
            args=(self.account.uuid,)
        )

crmapp/templates/communications/comm_cru.html
{% extends 'base.html' %}
{% block title %}Communication Operation{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <h4 class="ad-mh">Add a Communication</h4>
        {% include 'communications/comm_item_form.html' %}
    </div>
{% endblock content %}

crmapp/templates/communications/comm_detail.html
{% extends 'base.html' %}
{% block title %}Communication Detail{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <ul id="co-list" class="strip-list col-md-12 p-none">
            {% include 'communications/comm_item_view.html' %}
        </ul>
    </div>
{% endblock %}

crmapp/templates/communications/comm_item_form.html
<form id="comm-form"
      {# POST Destination #}
      action="{% if comm.uuid %}
      {% url 'comm_update' comm.uuid %}{% else %}{% url 'comm_new'%}{% endif %}"
      method="post">
    {% csrf_token %}
    <p>{{ form.subject }}</p>
    <div id="comm-form-internals">
        <p>{{ form.subject.errors }}</p>
        <p>{{ form.notes }}</p>
        <p>{{ form.notes.errors }}</p>
        <table class="table comm-form">
            <tbody>
                <tr>
                    <td>{{ form.kind }}</td>
                    <td>{{ form.date }}</td>
                    <td class="comm-submit-td">
                        <input class="btn btn-success comm-submit"
                               type="submit" value="SAVE"/></td>
                </tr>
                <tr>
                    <td>{{ form.kind.errors }}</td>
                    <td>{{ form.date.errors }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>

    <input id="id_account" name="account"
           type="hidden"
           value="{% if request.GET.account %}
           {{ request.GET.account }}{% else %}{{ account.id }}{% endif %}"/>
    <input id="id_owner" name="owner" type="hidden" value="{{ user.username }}"/>
</form>

crmapp/templates/communications/comm_item_view.html
<li class="co-item">
    <h5 class="co-item-h">{{ comm.subject }}
        <span>
            {# Comm Delete URL #}
            <a class="cancel comm-control" href="{{ comm.get_delete_url }}?account={{ account.id }}"></a>

            {# Comm Edit URL #}
            <a class="pen comm-control comm-edit"
     href="{{ comm.get_update_url }}?account={{ account.id }}"></a>

        </span>
    </h5>
    <p class="co-item-date">on {{ comm.date }}</p>
    <p>{{ comm.notes }}</p>
</li>